title: "000. [120583 / 프로그래머스] 중복된 숫자 개수"
labels: ["General Introduction"]
body:
  - type: markdown
    attributes:
      value: |
        문제 해결에 대한 생각을 작성하기
  - type: textarea
    id: improvements
    attributes:
      label: 문제 풀이
      description: "풀이 방법"
      value: |
        문제 주소: 
        ```

        ```
        
      render: bash
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: 내가 느낀 문제 난이도
      options:
        - label: ⭐️
          required: true
        - label: ⭐️⭐️
        - label: ⭐️⭐️⭐️
        - label: ⭐️⭐️⭐️⭐️
        - label: ⭐️⭐️⭐️⭐️⭐️